version: '3.8'

services:
  zonos:
    build: .
    image: zonos-local
    ports:
      - "8181:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]